export default {
  CREATE_COURSE: "CREATE_COURSE",
  LOAD_COURSES_SUCCESS: "LOAD_COURSES_SUCCESS",
  LOAD_AUTHOR_SUCCESS: "LOAD_AUTHOR_SUCCESS",
  CREATE_COURSE_SUCCESS: "CREATE_COURSE_SUCCESS",
  UPDATE_COURSE_SUCCESS: "UPDATE_COURSE_SUCCESS",
  DELETE_COURSE_SUCCESS:"DELETE_COURSE_SUCCESS"
}
